### PR TITLE
Add declare statement with defined symbols

### PR DESCRIPTION
**Pull request by wilkerlucio**
Adding this declare will make IDE's like Cursive able to index and auto-complete on the variables provided by csk.

### CODE REVIEW

**Comment by wilkerlucio** [comment]
Hello @qerub , thanks for merging this! Can you please make a release with the new changes? Or maybe add deps support so we could use the github version?

Thanks.

**Comment by qerub** [comment]
@wilkerlucio: I've added support for deps and verified that `echo "(require 'camel-snake-kebab.core)" | clj -Sdeps '{:deps {github-clj-commons/camel-snake-kebab {:git/url "https://github.com/clj-commons/camel-snake-kebab" :sha "8ae05909385c7a3e6a57ed4dfa7305ad09d18ddd"}}}' -` works for me.

**Comment by qerub** [comment]
@wilkerlucio: 0.4.1 is up now: https://clojars.org/camel-snake-kebab/versions/0.4.1

**Comment by wilkerlucio** [comment]
🎉 thanks!

**Pull request merged**
